---
- name: add repositories
  tags: base
  copy: src=files/{{ dir_pre | default }}/etc/yum.repos.d/{{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo owner=root group=root mode=0644
  with_items:
  - epel
  - qnib

- name: stop firewalld
  tags: base
  service: name=firewalld state=stopped enabled=no

- name: disable selinux
  tags: base
  selinux: state=disabled

